FROM nginx:1.19

ARG PROXY=""
ENV HTTP_PROXY $PROXY
ENV HTTPS_PROXY $PROXY
ENV http_proxy $PROXY
ENV https_proxy $PROXY

RUN apt-get update -y \
    && apt-get install -y apache2-utils \
    && rm -rf /var/lib/apt/lists/*

ENV BASIC_USERNAME=placeholder
ENV BASIC_PASSWORD=placeholder

ENV FORWARD_HOST=localhost
ENV FORWARD_PORT=8765

WORKDIR /
COPY nginx-basic-auth.conf nginx-basic-auth.conf

COPY run-nginx.sh ./
RUN chmod 0755 ./run-nginx.sh
CMD [ "sh", "/run-nginx.sh" ]
